### ISSUE TITLE
[Q] continuous control experiments

### ISSUE THREAD

**Issue by Howuhh** [schmidtdominik/LAPO#2]
Hi! Just wanted to find out a few details about the cheetah/walker experiments.
1. were these environments from deepmind control suite?
2. was the training done on pixels or real states?

**Comment by schmidtdominik** [comment]
Thanks for your question @Howuhh,

1. Yes, the continuous control experiments use the `cheetah_run` and `walker_walk` environments from the DeepMind Control Suite.
2. The training was done from pixels, analogous to our procgen experiments. Here is the env setup code for reference:

```python
import shimmy
from dm_control import suite
from dm_control.suite.wrappers import pixels

def _create_single_dmc_env(env_id):
    domain_name, task_name = env_id.split("_")
    env = suite.load(domain_name=domain_name, task_name=task_name)
    env = pixels.Wrapper(env)
    env = shimmy.dm_control_compatibility.DmControlCompatibilityV0(env)
    env = gym.wrappers.TransformObservation(env, lambda obs: obs["pixels"])
    env.observation_space = gym.spaces.Box(0, 255, (64, 64, 3), np.uint8)
    env = gym.wrappers.RecordEpisodeStatistics(env)
    env = gym.wrappers.ResizeObservation(env, (64, 64))
    return env
```
